version: '3.8'
    
services:
    nodejs_docker:
        container_name: nodejs_docker
        image: nodejs_docker:1.0
        build: .
        expose:
            - 8080
        ports:
            - "104.42.216.225:8080:8080"
        environment: 
            APP_PORT: 8080